-- DDL
-- CREATE
-- ALTER
-- DROP

CREATE DATABASE db_redesocial


USE db_redesocial

CREATE TABLE Usuarios(
	Id INT PRIMARY KEY NOT NULL,
	Nome VARCHAR(50) NOT NULL,
	Email VARCHAR(50) NOT NULL,
	Senha VARCHAR(100) NOT NULL
)

CREATE TABLE Postagem(
	Id INT PRIMARY KEY NOT NULL,
	Descricao VARCHAR(50) NOT NULL,
	Tema VARCHAR (50) NOT NULL,
	FK_Usuarios INT NOT NULL,
	FK_Grupos INT NOT NULL,
	FOREIGN KEY (FK_Usuarios) REFERENCES Usuarios (Id),
	FOREIGN KEY (FK_Grupos) REFERENCES Grupos (Id)
)

CREATE TABLE Grupos(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	Nome VARCHAR(50) NOT NULL,
	Assunto VARCHAR(150) NOT NULL,
	Integrantes Varchar(MAX) NOT NULL,
)

